Profcess_Dev/urls.py
from django.contrib import admin
from django.urls import path, include
# from test_app import views
from accounts import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("findJob/", views.findJob, name="findJob"),
    path("careerAdvice/", views.careerAdvice, name="careerAdvice"),
    path("findATalent/", views.findATalent, name="findATalent"),
    path("services/", views.services, name="services"),
    path("contact/", views.contact, name="contact"),
    path("accounts/", include('accounts.urls')),
    path("recruiter/", include("recruiter_app.urls")),
    path("applicant/", include("applicant_app.urls")),
    path("college/",include("college_app.urls")),
    path("select2/", include("django_select2.urls")),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
     path('converter/',include('htmltopdf.urls'),name="converter"),
    # path("signup/", views.signup, name = "signup")
]

accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('index/',views.index,name="index"),
    path('recruiter-signup/', views.recruiter_signup, name="recruiter-signup"),
    path('activate/<uid>/<token>/', views.activate, name='activate'),
    path('applicant-signup/', views.ApplicantSignUp, name="applicant-signup"),
    path('college-signup/', views.college_signup, name="college-signup"),
    path('email_form/',views.email_form,name="email_form"),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change_form.html",
                                                                   success_url=reverse_lazy(
                                                                       "accounts:password_change_done")),
         name="password_change"),
    path('change-password/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"),
         name="password_change_done"),
    path('applicant-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('applicant-signup/terms.html', views.showterms, name="showterms"),
    path('recruiter-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('recruiter-signup/terms.html', views.showterms, name="showterms"),
    path('college-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('college-signup/terms.html', views.showterms, name="showterms"),
    path('about/', views.about, name="about"),
]


recruiter_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from recruiter_app.views import job_detail, Update_job,Delete_job,my_candidates,job_matching,search_candidates,campus_hiring,add_a_blog,assessments,recruiter_blog,applicant_detail


app_name = 'recruiter'

urlpatterns = [
    path("create-recruiter-user-profile/",
         views.createprofile, name="create_recruiter_profile"),
    path("profile/",views.profile,name="profile"),
    path("create-job/", views.createjob, name="create_job"),
    path("posted-jobs/", views.posted_jobs, name="posted_jobs"),
    path("job-detail/<int:pk>", views.job_detail, name="job_detail"),
    path("job-detail/<int:pk>/update/", Update_job.as_view(), name = "update_job"),
    path("job-detail/<int:pk>/delete/", Delete_job.as_view(), name = "delete_job"),
    path("search-candidates/",views.search_candidates,name="search_candidates"),
    path("my-candidate/", views.my_candidates, name="my_candidates"),
    path("job-matching/<int:pk>", views.job_matching, name="job_matching"),
    path("campus-hiring/", views.campus_hiring, name="campus_hiring"),
    path("assessments/", views.assessments, name="assessments"),
    path("add-a-blog/", views.add_a_blog, name="add_a_blog"),
    path("recruiter-blog/", views.recruiter_blog, name="recruiter_blog"),
    path("applicant-detail/<int:pk>", views.applicant_detail, name="applicant_detail"),
    path("can/<int:pk>/<int:mk>/",views.can,name="can"),
    path("alreadycan/<int:pk>/",views.alreadycan,name="alreadycan"),
    path("pricing/",views.pricing,name="pricing"),
    path("purchase-plan/",views.purchase_plan,name="purchase-plan")



    # path('login/', auth_views.LoginView.as_view(),name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    # path('recruiter-signup/', views.RecruiterSignUp.as_view(), name="recruiter-signup"),
    # path('applicant-signup/', views.ApplicantSignUp.as_view(), name="applicant-signup"),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name = "accounts/password_change_form.html", success_url = reverse_lazy("accounts:password_change_done")), name = "password_change"),
    # path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/password_change_done.html"), name = "password_change_done"),


]

recruiter_app/models.py
from django.db import models
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.urls import reverse
from datetime import datetime
from multiselectfield import MultiSelectField


# Create your models here.
from accounts.models import ProfcessUser
from applicant_app.models import ApplicantUserProfile
User = ProfcessUser
can=ApplicantUserProfile



class RecruiterUserProfile(models.Model):
    name = models.CharField(blank=True, max_length=140)
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        limit_choices_to={"usertype": "Recruiter"},
        related_name="recruiteruserprofile"
    )
    location = models.CharField(blank=True, max_length=140)
    #cell = models.CharField('Contact Phone', blank=True, max_length=10,
                               #validators=[MaxLengthValidator(10), MinLengthValidator(10)])
    #HR_email = models.EmailField('Email Address', blank=True)
    designation=models.CharField(default='',blank=True, max_length=140)
    company_name=models.CharField(default='',blank=True, max_length=140)
    Url_of_company=models.CharField(default='',blank=True, max_length=140)
    why_join_us=models.CharField(default='',blank=True, max_length=540)
    company_description=models.CharField(blank=True, max_length=540)

    def __str__(self):
        return self.name
    pass
    
class Job(models.Model):
    job_title = models.CharField(blank=True, max_length=140)
    posted_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        limit_choices_to={"usertype": "Recruiter"},
        related_name="jobs",
        default="def",
        blank=True)
    applied_by = models.ManyToManyField(
        User,
        related_name="applied_by",
        limit_choices_to={"usertype": "Applicant"},
        blank=True)
    company_name = models.CharField('company name', max_length=30, blank=True)

    job_salary = models.CharField('MONTHLY HAND IN SALARY', blank=True, max_length=140)
    job_vacancies = models.IntegerField('NO. OF OPENINGS', default=1, blank=True)
    TYPE_OF_JOB_CHOICES = [
        ('full time', 'FULL TIME'),
        ('contract', 'CONTRACT'),
        ('part time', 'PART TIME'),
        ('internship', 'INTERNSHIP'),
        ('volunteer', 'VOLUNTEER'),
        ('temporary', 'TEMPORARY'),
        ('remote', 'REMOTE'),
    ]
    type_of_job = models.CharField('TYPE OF JOB',
                                   max_length=35,
                                   choices=TYPE_OF_JOB_CHOICES,
                                   default=""
                                   )
    JOB_LOCATION_CHOICES = [
        ('wfh', 'Work From Home'),
        ('ahemdabad', 'Ahmedabad'),
        ('bengaluru', 'Bengaluru'),
        ('chennai', 'Chennai'),
        ('delhi', 'Delhi'),
        ('hydradad', 'Hyderabad'),
        ('jaipur', 'Jaipur'),
        ('kolkata', 'Kolkata'),
        ('mumbai', 'Mumbai'),
        ('pune', 'Pune'),
        ('surat', 'Surat'),
        ('vishakhapatnam', 'Vishakhapatnam')
    ]
    SKILLS = (
        ('JAVA', 'JAVA'),
        ('CPP', 'CPP'),
        ('C', 'C'),
        ('Python', 'Python'),
        ('jQuery', 'jQuery'),
        ('Javascript', 'Javascript')
    )

    job_location = models.CharField('JOB LOCATION',
                                    max_length=35,
                                    choices=JOB_LOCATION_CHOICES,
                                    default=""
                                    )
    job_requirements =  MultiSelectField(
                                        choices=SKILLS,
                                        max_length=540
                                        )
    job_info = models.CharField(blank=True,
                                max_length=540)
    date = models.DateTimeField('Expected Hiring Date', auto_now_add=False, auto_now=False, blank=True, null=True)
    work_choice = models.CharField('Does this job allow hires to work remote?', max_length=100, default="",
                                   choices=[('Yes', 'Yes'),
                                            ('No', 'No'),
                                            ('Temporary due to COVID-19', 'Temporary due to COVID-19')
                                            ])
    # job_starting_date = models.DateTimeField(
    #     verbose_name=_('Date joined'), auto_now_add=True)

    def __str__(self):
        return self.job_title
    pass

    def  get_absolute_url(self):    # redirect to job details after updation
        return reverse('recruiter:job_detail' , kwargs={'pk': self.pk})
class Short_list_candidate(models.Model):
    candidate=models.ForeignKey(
        can,on_delete=models.CASCADE)
    jobs=models.ManyToManyField(Job)
    def _str_(self):
        return self.name
class UserData(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        limit_choices_to={"usertype": "Recruiter"},
    )
    token = models.IntegerField(null=True, blank=True,default=10)

    def str(self):
        return self.user.username

recruiter_app/forms.py
from django import forms
from multiselectfield import MultiSelectFormField
from django_select2.forms import Select2MultipleWidget

from .models import RecruiterUserProfile, Job, ProfcessUser,UserData


class UserProfileForm(forms.ModelForm):
	name = forms.CharField(max_length=140, widget=forms.TextInput(attrs={'class': 'form-control'}))
	location = forms.CharField(max_length=140, widget=forms.TextInput(attrs={'class': 'form-control'}))
	designation = forms.CharField(max_length=140, widget=forms.TextInput(attrs={'class': 'form-control'}))
	company_name = forms.CharField(max_length=140, widget=forms.TextInput(attrs={'class': 'form-control'}))
	Url_of_company = forms.CharField(max_length=140, widget=forms.TextInput(attrs={'class': 'form-control'}))
	why_join_us = forms.CharField(max_length=540, widget=forms.TextInput(attrs={'class': 'form-control'}))
	# cell = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'class': 'form-control'}))
	# HR_email = forms.EmailField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
	company_description = forms.CharField(max_length=540, widget=forms.TextInput(attrs={'class': 'form-control'}))

	class Meta:
		model = RecruiterUserProfile
		fields = (
		"name", "location", "designation", "company_name", "Url_of_company", "why_join_us", "company_description")

	pass


class JobCreationForm(forms.ModelForm):
	job_requirements = forms.MultipleChoiceField(choices=Job.SKILLS)

	class Meta:
		model = Job

		widgets = {
			'work_choice': forms.RadioSelect()
		}
		fields = (
			"job_title", "job_vacancies", "company_name", "job_salary", "type_of_job", "job_location",
			"job_requirements", "job_info",
			"work_choice", "date")

		pass


class JobUpdationForm(forms.ModelForm):
	job_requirements = forms.MultipleChoiceField(choices=Job.SKILLS)

	class Meta:
		model = Job
		widgets = {
			'work_choice': forms.RadioSelect()
		}
		fields = (
			"job_title", "job_vacancies", "company_name", "job_salary", "type_of_job", "job_location",
			"job_requirements", "job_info",
			"work_choice", "date")

	def save(self, commit=True):
		job = self.instance
		job.job_title = self.cleaned_data['job_title']
		job.job_vacancies = self.cleaned_data['job_vacancies']
		job.company_name = self.cleaned_data['company_name']
		job.job_salary = self.cleaned_data['job_salary']
		job.job_info = self.cleaned_data['job_info']
		job.job_requirements = self.cleaned_data['job_requirements']
		job.job_location = self.cleaned_data['job_location']
		job.date = self.cleaned_data['date']
		job.work_choice = self.cleaned_data['work_choice']
		if commit:
			job.save()
		return job


class DetailUpdateForm(forms.ModelForm):
	class Meta:
		model = RecruiterUserProfile
		fields = ["name", "location", "designation", "company_name", "Url_of_company", "why_join_us",
				  "company_description"]


class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = ProfcessUser
		fields = ['username', 'email', "first_name", "last_name", "phone", "company_name", "designation", "location",
				  "url_of_company", "why_join_us", "company_description", ]

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = UserData
		fields = ['token']

recruiter_app/templates/recruiter_app/assessments.html
{% extends "dashboard.html" %}
{% block content %}
<h1>
    Assessments
</h1>
{% endblock content %}

recruiter_app/templates/recruiter_app/job_detail.html
{% extends "dashboard.html" %}

{% block content %}
<!-- Script -->

<!-- CSS -->
    <div class="card-header bg-transparent border-0">
                <h1>Best Candidates </h1>
    </div>
{% if qs %}
    <div class="card-body">
                <div class="alert alert-primary" role="alert">
                You have  {{ count }} best Candidates!
                </div>
    </div>
    <div class="table-responsive">
        <div>
            <table class="table align-items-center">
                <thead class="thead-light">
                <tr>
                    <th scope="col" class="sort" data-sort="name">Username</th>
                    <th scope="col" class="sort" data-sort="location">Location</th>
                    <th scope="col" class="sort" data-sort="skills">Skills</th>
                    <th scope="col" class="sort" data-sort="skills">Education</th>
                </tr>
                </thead>

                {% for qss in qs %}
                <tbody class="list">
                <tr>
                    <th scope="row">
                        <div class="media-body">
                            <a href="{% url 'recruiter:applicant_detail' pk=qss.pk %}">
                                <span class="name mb-0 text-sm">{{ qss.user }}</span>
                            </a>
                        </div>
                    </th>
                    <td>
                    <span class="name mb-0 text-sm">{{ qss.location }}</span>
                    </td>
                    <td>
                        <span class="name mb-0 text-sm">{{ qss.area_of_expertise }}</span>
                    </td>
                    <td>
                    <span class="name mb-0 text-sm">{{ qss.education }}</span>
                    </td>
                </tr>

            {% endfor %}
                </tbody>
            </table>{% else %}
            <div class="card-body">
                <div class="alert alert-primary" role="alert">
                You dont have any Candidates!
                </div>
    </div>
            {% endif %}
        </div>
    </div>
    <br><br><br>
    <div>
    <div class="card-header bg-transparent border-0">
                <h1>Candidates Applied for the job</h1>
    </div>
        {% if qs1 %}
    <div class="card-body">
                <div class="alert alert-primary" role="alert">
                 You have {{ count1 }} Applied for the job!
                </div>

    <div class="table-responsive">
        <div>
            <table class="table align-items-center">
                <thead class="thead-light">
                <tr>
                    <th scope="col" class="sort" data-sort="name">Username</th>
                    <th scope="col" class="sort" data-sort="location">Location</th>
                    <th scope="col" class="sort" data-sort="skills">Skills</th>
                    <th scope="col" class="sort" data-sort="skills">Education</th>
                </tr>
                </thead>

                {% for apply in qs1 %}
                <tbody class="list">
                <tr>
                    <th scope="row">
                        <div class="media-body">
                            <a href="{% url 'recruiter:applicant_detail' pk=apply.pk %}">
                                <span class="name mb-0 text-sm">{{ apply.user }}</span>
                            </a>
                        </div>
                    </th>
                    <td>
                    <span class="name mb-0 text-sm">{{ apply.location }}</span>
                    </td>
                    <td>
                        <span class="name mb-0 text-sm">{{ apply.area_of_expertise }}</span>
                    </td>
                    <td>
                    <span class="name mb-0 text-sm">{{ apply.education }}</span>
                    </td>
                </tr>

            {% endfor %}
                </tbody>
            </table>{% else %}

                <div class="alert alert-primary" role="alert">
                 You dont have any Candidates!
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    </div>
<div>

    <div class="header bg-primary pb-6" >
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-13">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Job Details</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item active" aria-current="page">jobDetail</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--6">
        <div class="row justify-content-center">
            <div class="col-md-8 col-12">
                <div class="card card-pricing border-0 text-center mb-4">
                    <div class="card-header bg-transparent">

                        <div class="display-2">{{ job.job_title }}</div>
                        <span class=" text-muted">Posted By: {{ job.posted_by }}</span>

                    </div>
                    <div class="card-body px-lg-7">
                        <ul class="list-unstyled my-4">
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-terminal"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">Job Salary: {{ job.job_salary }}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-pen-fancy"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">job vacancies: {{job.job_vacancies}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-pen-fancy"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">Company name: {{job.company_name}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">Type of Job :{{job.type_of_job}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">job Location :{{job.job_location}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">job Requirements: {{job.job_requirements}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">job Info: {{job.job_info}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">Hiring Date:{{job.date}}</span>
                                    </div>
                                </div>
                            </li>
                            <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">Does this job allows to work you remotely:{{job.work_choice}}</span>
                                    </div>
                                </div>
                            </li>
                        </ul>

                        <a class="btn btn-secondary" href="{% url 'recruiter:update_job' pk=job.pk %}">Edit</a>
                        <a class="btn btn-danger" href="{% url 'recruiter:delete_job' pk=job.pk %}">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

recruiter_app/templates/recruiter_app/search_candidates.html
{% extends "dashboard.html" %} {% block content %}

    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Candidates</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item"><a href="{% url 'recruiter:search_candidates' %}"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item active" aria-current="page">Candidates for you</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
<div class="container">
            <div class="row justify-content-center">
                <div id="searchForm" class="col-md-10 col-10">
                    <h3 class="m-2">I'm looking for -</h3>
                    <ul class="nav" id="searchTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link" id="people-tab" data-toggle="tab" href="#people" role="tab"
                               aria-controls="people" aria-selected="false"><h3>People</h3></a>
                        </li>
                    </ul>
                    <div class="tab-content" id="searchTabContent">
                        <div class="tab-pane fade show active" id="job" role="tabpanel" aria-labelledby="job-tab">
                            <form id="jobSearchForm" method="get">
                                <div class="row align-items-end">
                                    <div class="col-md-7 col-12">
                                        <label class="" for="jobs"></label>
                                        <input type="text" class="form-control" id="candidate" name="q"
                                               placeholder="Search by title, skills or location">
                                    </div>


                                    <div class="col-md-1 col-12 text-center">
                                        <label class="d-none d-sm-block" for="searchBtn"></label>
                                        <button type="submit" class="btn btn-primary fa fa-search"></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
</div>

<br><br><br><br><br>
    <div class="container-fluid mt--6">
        <div class="row justify-content-center">
            <div class="col-md-8 col-12">
                <div class="card">
                    {% if m %}


                    <!-- Card header -->
                    <div class="card-header bg-transparent border-0">
                        <span> Click on the candidates to view candidate detail.</span>
                    </div>

                    <div class="card-body">
                            <ul class="list-group list-group-flush">
                                {% for can in m %}
                                    <a href="{% url 'recruiter:applicant_detail' pk=can.pk %}">
                                        <li class="list-group-item">{{ can.user }}</li>
                                    </a>

                            </ul>
                                {% endfor %}
                        {% else %}
                        <div class="card-header bg-transparent border-0">
                        <span> NO result found</span>
                    </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
<script type="text/javascript">
    document.getElementById("candidate").value="{{ query }}
</script>

{% endblock content %}