Profcess_Dev/urls.py
from django.contrib import admin
from django.urls import path, include
# from test_app import views
from accounts import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("findJob/", views.findJob, name="findJob"),
    path("careerAdvice/", views.careerAdvice, name="careerAdvice"),
    path("findATalent/", views.findATalent, name="findATalent"),
    path("services/", views.services, name="services"),
    path("contact/", views.contact, name="contact"),
    path("accounts/", include('accounts.urls')),
    path("recruiter/", include("recruiter_app.urls")),
    path("applicant/", include("applicant_app.urls")),
    path("college/",include("college_app.urls")),
    path("select2/", include("django_select2.urls")),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
     path('converter/',include('htmltopdf.urls'),name="converter"),
    # path("signup/", views.signup, name = "signup")
]

accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('index/',views.index,name="index"),
    path('recruiter-signup/', views.recruiter_signup, name="recruiter-signup"),
    path('activate/<uid>/<token>/', views.activate, name='activate'),
    path('applicant-signup/', views.ApplicantSignUp, name="applicant-signup"),
    path('college-signup/', views.college_signup, name="college-signup"),
    path('email_form/',views.email_form,name="email_form"),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change_form.html",
                                                                   success_url=reverse_lazy(
                                                                       "accounts:password_change_done")),
         name="password_change"),
    path('change-password/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"),
         name="password_change_done"),
    path('applicant-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('applicant-signup/terms.html', views.showterms, name="showterms"),
    path('recruiter-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('recruiter-signup/terms.html', views.showterms, name="showterms"),
    path('college-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('college-signup/terms.html', views.showterms, name="showterms"),
    path('about/', views.about, name="about"),
]


college_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from college_app.views import Update_job,Delete_job
#from college_app.views import job_detail, Update_job,Delete_job,my_candidates,job_matching,search_candidates,campus_hiring,add_a_blog,assessments,recruiter_blog,applicant_detail


app_name = 'college'

urlpatterns = [
    path("create-college-user-profile/",
         views.createprofile, name="create_college_profile"),
    path("profile/",views.profile,name="profile"),
    path("create-job/", views.createjob, name="create_job"),
    path("posted-jobs/", views.posted_jobs, name="posted_jobs"),
    path("job-detail/<int:pk>", views.job_detail, name="job_detail"),
    path("job-detail/<int:pk>/update/", Update_job.as_view(), name = "update_job"),
    path("job-detail/<int:pk>/delete/", Delete_job.as_view(), name = "delete_job"),
    path("college-app/profile/",views.profile,name="profile"),
    #path("search-candidates/",views.search_candidates,name="search_candidates"),
    #path("my-candidate/", views.my_candidates, name="my_candidates"),
    #path("job-matching/<int:pk>", views.job_matching, name="job_matching"),
    #path("campus-hiring/", views.campus_hiring, name="campus_hiring"),
    #path("assessments/", views.assessments, name="assessments"),
    #path("add-a-blog/", views.add_a_blog, name="add_a_blog"),
    #path("recruiter-blog/", views.recruiter_blog, name="recruiter_blog"),
    #path("applicant-detail/<int:pk>", views.applicant_detail, name="applicant_detail"),
    #path("can/<int:pk>/<int:mk>/",views.can,name="can"),
    #path("alreadycan/<int:pk>/",views.alreadycan,name="alreadycan")



    # path('login/', auth_views.LoginView.as_view(),name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    # path('recruiter-signup/', views.RecruiterSignUp.as_view(), name="recruiter-signup"),
    # path('applicant-signup/', views.ApplicantSignUp.as_view(), name="applicant-signup"),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name = "accounts/password_change_form.html", success_url = reverse_lazy("accounts:password_change_done")), name = "password_change"),
    # path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/password_change_done.html"), name = "password_change_done"),


]

recruiter_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from recruiter_app.views import job_detail, Update_job,Delete_job,my_candidates,job_matching,search_candidates,campus_hiring,add_a_blog,assessments,recruiter_blog,applicant_detail


app_name = 'recruiter'

urlpatterns = [
    path("create-recruiter-user-profile/",
         views.createprofile, name="create_recruiter_profile"),
    path("profile/",views.profile,name="profile"),
    path("create-job/", views.createjob, name="create_job"),
    path("posted-jobs/", views.posted_jobs, name="posted_jobs"),
    path("job-detail/<int:pk>", views.job_detail, name="job_detail"),
    path("job-detail/<int:pk>/update/", Update_job.as_view(), name = "update_job"),
    path("job-detail/<int:pk>/delete/", Delete_job.as_view(), name = "delete_job"),
    path("search-candidates/",views.search_candidates,name="search_candidates"),
    path("my-candidate/", views.my_candidates, name="my_candidates"),
    path("job-matching/<int:pk>", views.job_matching, name="job_matching"),
    path("campus-hiring/", views.campus_hiring, name="campus_hiring"),
    path("assessments/", views.assessments, name="assessments"),
    path("add-a-blog/", views.add_a_blog, name="add_a_blog"),
    path("recruiter-blog/", views.recruiter_blog, name="recruiter_blog"),
    path("applicant-detail/<int:pk>", views.applicant_detail, name="applicant_detail"),
    path("can/<int:pk>/<int:mk>/",views.can,name="can"),
    path("alreadycan/<int:pk>/",views.alreadycan,name="alreadycan"),
    path("pricing/",views.pricing,name="pricing"),
    path("purchase-plan/",views.purchase_plan,name="purchase-plan")



    # path('login/', auth_views.LoginView.as_view(),name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    # path('recruiter-signup/', views.RecruiterSignUp.as_view(), name="recruiter-signup"),
    # path('applicant-signup/', views.ApplicantSignUp.as_view(), name="applicant-signup"),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name = "accounts/password_change_form.html", success_url = reverse_lazy("accounts:password_change_done")), name = "password_change"),
    # path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/password_change_done.html"), name = "password_change_done"),


]

college_app/models.py
from django.db import models
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.urls import reverse
from multiselectfield import MultiSelectField

# Create your models here.
from accounts.models import ProfcessUser
User = ProfcessUser
class CollegeUserProfile(models.Model):
    name = models.CharField(blank=True, max_length=140)
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        limit_choices_to={"usertype": "College"},
        related_name="collegeuserprofile"
    )
    location = models.CharField(blank=True, max_length=140)
    #cell = models.CharField('Contact Phone', blank=True, max_length=10,
                               #validators=[MaxLengthValidator(10), MinLengthValidator(10)])
    #HR_email = models.EmailField('Email Address', blank=True)
    designation=models.CharField(default='',blank=True, max_length=140)
    college_name=models.CharField(default='',blank=True, max_length=140)
    url_of_college=models.CharField(default='',blank=True, max_length=140)
    why_join_us=models.CharField(default='',blank=True, max_length=540)
    college_description=models.CharField(blank=True, max_length=540)

    def __str__(self):
        return self.name
    pass
class Job(models.Model):
    job_title = models.CharField(blank=True, max_length=140)
    posted_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        limit_choices_to={"usertype": "College"},
        related_name="college_jobs",
        default="def",
        blank=True)
    applied_by = models.ManyToManyField(
        User,
        related_name="applied_by_students",
        limit_choices_to={"usertype": "Applicant"},
        blank=True)
    company_name = models.CharField('company name', max_length=30, blank=True)

    job_salary = models.CharField('MONTHLY HAND IN SALARY', blank=True, max_length=140)
    job_vacancies = models.IntegerField('NO. OF OPENINGS', default=1, blank=True)
    TYPE_OF_JOB_CHOICES = [
        ('full time', 'FULL TIME'),
        ('contract', 'CONTRACT'),
        ('part time', 'PART TIME'),
        ('internship', 'INTERNSHIP'),
        ('volunteer', 'VOLUNTEER'),
        ('temporary', 'TEMPORARY'),
        ('remote', 'REMOTE'),
    ]
    type_of_job = models.CharField('TYPE OF JOB',
                                   max_length=35,
                                   choices=TYPE_OF_JOB_CHOICES,
                                   default=""
                                   )
    JOB_LOCATION_CHOICES = [
        ('wfh', 'Work From Home'),
        ('ahemdabad', 'Ahmedabad'),
        ('bengaluru', 'Bengaluru'),
        ('chennai', 'Chennai'),
        ('delhi', 'Delhi'),
        ('hydradad', 'Hyderabad'),
        ('jaipur', 'Jaipur'),
        ('kolkata', 'Kolkata'),
        ('mumbai', 'Mumbai'),
        ('pune', 'Pune'),
        ('surat', 'Surat'),
        ('vishakhapatnam', 'Vishakhapatnam')
    ]
    job_location = models.CharField('JOB LOCATION',
                                    max_length=35,
                                    choices=JOB_LOCATION_CHOICES,
                                    default=""
                                    )
    SKILLS = (
        ('JAVA', 'JAVA'),
        ('CPP', 'CPP'),
        ('C', 'C'),
        ('Python', 'Python'),
        ('jQuery', 'jQuery'),
        ('Javascript', 'Javascript')
    )
    job_requirements = MultiSelectField(choices=SKILLS,
                                        blank=True,
                                        max_length=540)
    job_info = models.CharField(blank=True,
                                max_length=540)
    date = models.DateTimeField('Expected Hiring Date', auto_now_add=False, auto_now=False, blank=True, null=True)
    work_choice = models.CharField('Does this job allow hires to work remote?', max_length=100, default="",
                                   choices=[('Yes', 'Yes'),
                                            ('No', 'No'),
                                            ('Temporary due to COVID-19', 'Temporary due to COVID-19')
                                            ])
    # job_starting_date = models.DateTimeField(
    #     verbose_name=_('Date joined'), auto_now_add=True)

    def __str__(self):
        return self.job_title
    pass

    def  get_absolute_url(self):    # redirect to job details after updation
        return reverse('college:job_detail' , kwargs={'pk': self.pk})

college_app/views.py
from django.shortcuts import render
from .forms import UserProfileForm,UserUpdateFormCollege,Job,JobUpdationForm,JobCreationForm
from .models import CollegeUserProfile
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView, DeleteView

# Create your views here.
@login_required
def createprofile(request):
	if request.method == "POST":
		form = UserProfileForm(request.POST)
		if form.is_valid():
			userprofile = form.save(commit=False)
			userprofile.user = request.user
			userprofile.save()
			return render(request, "college_app/thanks.html")  # return page after filling userinfo form

		else:
			return "#########"

	else:
		form = UserProfileForm()
		return render(request, "college_app/userprofileform.html", {"form": form})
@login_required
def profile(request):


	if request.method == 'POST':
		c_form = UserUpdateFormCollege(request.POST, instance=request.user)

		if c_form.is_valid():
			c_form.save()
			return render(request, 'college_app/update_success.html')
	else:
		c_form = UserUpdateFormCollege(instance=request.user)
	context = {
		'c_form': c_form,

	}
	return render(request, 'college_app/profile.html', context)


@login_required
def createjob(request):
	if request.method == "POST":
		form = JobCreationForm(request.POST)
		if form.is_valid():
			job = form.save(commit=False)
			job.posted_by = request.user
			job.save()
			context = {
				"job": job,
			}
			context['job'] = job
			return render(request, "college_app/job_detail.html", context)  # return page after posting a new job
			pass
		else:
			pass
		pass
	else:
		form = JobCreationForm()
		return render(request, "college_app/createjob.html", {"form": form})
		pass


@login_required
def job_detail(request, pk=None):
	job = Job.objects.get(pk=pk)
	context={}
	context['job'] = job
	return render(request, "college_app/job_detail.html", context)

class Update_job(UpdateView):
	model = Job
	fields = (
	"job_title", "job_vacancies", "company_name", "job_salary", "type_of_job", "job_location", "job_requirements",
	"job_info", "date", "work_choice")
	template_name = 'college_app/createjob.html'

	def form_valid(self, form):
		form.instance.posted_by = self.request.user
		return super().form_valid(form)

class Delete_job(DeleteView):
	model = Job
	success_url = '/'
@login_required
def posted_jobs(request):
	jobs = request.user.college_jobs.all()
	context = {
		"jobs": jobs,
		"count": len(jobs),
	}
	return render(request, "college_app/posted_jobs.html", context)


college_app/templates/college_app/createjob.html
{% extends "dashboard.html" %}
{% load static %}
{% block content %}
{% block style %}
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
    <link rel="stylesheet" href="{% static 'css/gijgo.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/multiple-select.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.datetimepicker.css' %}">
{% endblock %}
<link rel="stylesheet" href="{% static 'css/gijgo.min.css' %}">
    <!-- Masthead-->
    <div class="container-fluid mt--6">
        <div class="row justify-content-center">
            <div class="col-md-8 col-12">
                <div class="card">
                    <div class="card-header">
                        <h1 class="mb-0">POST A JOB</h1>
                    </div>
                    <!-- Card body -->
                    <div class="card-body">
                        <form method="POST" class="form">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group row justify-content-center">
                                    <label for="example-text-input" class="col-md-3 col-4 col-form-label form-control-label">{{ field.label_tag }}</label>
                                    <div class="col-md-9 col-8">
                                        {{ field }}
                                        <script src="{% static 'js/jquery-3.5.1.min.js' %}" charset="utf-8"></script>
                                        <script src="{% static 'js/gijgo.min.js' %}" charset="utf-8"></script>
                                        <script src="{% static 'js/multiple-select.js' %}" charset="utf-8"></script>
                                        <script src="{% static 'js/jquery.datetimepicker.full.min.js' %}" charset="utf-8"></script>
                                        <script>
                                            $('#id_date').datetimepicker({
                                                format: 'm/d/Y H:i',
                                            });
                                            var v=document.getElementById("id_job_requirements");    
                                            var dat=[{
                                                text:"",
                                                value:""
                                            }];
                                            var v1=v.getElementsByTagName("li");
                                            for(var i=0;i<v1.length;i++)
                                            {   
                                                dat[i]={
                                                    text: v1[i].textContent,
                                                    value: v1[i].textContent
                                                }
                                            }
                                            if(dat.length>1){
                                                v.setAttribute("multiple",null);
                                                $('#id_job_requirements').multipleSelect({
                                                    multiple: true,
                                                    data:dat,
                                                    filter: true,
                                                    multipleWidth: 300,
                                                    maxHeight: 150,
                                                    width: 300,
                                                    dropWidth: 300,
                                                    displayHtml: false,
                                                    displayValues: true,
                                                    displayTitle: true,
                                                    minimumCountSelected: 10,
                                                    keepOpen: true,
                                                    showClear: true,
                                                    placeholder: 'Select Skills',
                                                 });
                                            }
                                            else{
                                                $('#id_job_requirements').multipleSelect({
                                                    multiple: true,
                                                    filter: true,
                                                    multipleWidth: 300,
                                                    maxHeight: 150,
                                                    width: 300,
                                                    dropWidth: 300,
                                                    displayHtml: false,
                                                    displayValues: true,
                                                    displayTitle: true,
                                                    minimumCountSelected: 10,
                                                    keepOpen: true,
                                                    showClear: true,
                                                    placeholder: 'Select Skills',
                                                 });
                                            }
                                        </script>
                                    </div>
                                </div>
                            {% endfor %}

                                <div class="text-center">
                                <button type="submit" class="btn btn-primary">POST JOB</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

college_app/templates/college_app/job_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <!-- Masthead-->
<header class="masthead auth">
  <div class="container">
  <div class="row">
    <div class="col-md-4 col-xs-8 formDesign">
    <h1>DELETE JOB ?</h1>
      <form method="POST" class="form">
        {% csrf_token %}
        {{form.as_p}}
        <h2>Are you sure you want to delete the {{job.job_title}}?</h2>
        <button type="submit" class="btn btn-outline-danger">DELETE</button>
        <a href="{% url 'recruiter:job_detail' pk=job.pk  %}" class="btn btn-secondary" >CANCEL</a>
      </form>
    </div>
    <div class="col-md-4 col-xs-2"></div>
  </div>
    
  </div>
</header>
{% endblock content %}

college_app/templates/college_app/job_detail.html
{% extends "dashboard.html" %}

{% block content %}
<!-- Script -->

<!-- CSS -->
    <div class="header bg-primary pb-6" >
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-13">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Job Details</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item active" aria-current="page">jobDetail</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--6">
        <div class="row justify-content-center">
            <div class="col-md-8 col-12">
                <div class="card card-pricing border-0 text-center mb-4">
                    <div class="card-header bg-transparent">

                        <div class="display-2">{{ job.job_title }}</div>
                        <span class=" text-muted">Posted By: {{ job.posted_by }}</span>

                    </div>
                    <div class="card-body px-lg-7">
                        <ul class="list-unstyled my-4">
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-terminal"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">Job Salary: {{ job.job_salary }}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-pen-fancy"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">job vacancies: {{job.job_vacancies}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-pen-fancy"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">Company name: {{job.company_name}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">Type of Job :{{job.type_of_job}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">job Location :{{job.job_location}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">job Requirements: {{job.job_requirements}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">job Info: {{job.job_info}}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">Hiring Date:{{job.date}}</span>
                                    </div>
                                </div>
                            </li>
                            <div class="d-flex align-items-center">
                                    <div>
                                        <div class="icon icon-xs icon-shape bg-gradient-primary text-white shadow rounded-circle">
                                            <i class="fas fa-hdd"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <span class="pl-2 text-sm">Does this job allows to work you remotely:{{job.work_choice}}</span>
                                    </div>
                                </div>
                            </li>
                        </ul>

                        <a class="btn btn-secondary" href="{% url 'college:update_job' pk=job.pk %}">Edit</a>
                        <a class="btn btn-danger" href="{% url 'college:delete_job' pk=job.pk %}">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

college_app/templates/college_app/thanks.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
      <h1>Thanks for filling up the profile.</h1>
  </div>
{% endblock content %}

college_app/templates/college_app/update_success.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
      <br><br><br><br><br>
      <h1>Profile Updated!!</h1>
  </div>
{% endblock content %}