Profcess_Dev/urls.py
from django.contrib import admin
from django.urls import path, include
# from test_app import views
from accounts import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("findJob/", views.findJob, name="findJob"),
    path("careerAdvice/", views.careerAdvice, name="careerAdvice"),
    path("findATalent/", views.findATalent, name="findATalent"),
    path("services/", views.services, name="services"),
    path("contact/", views.contact, name="contact"),
    path("accounts/", include('accounts.urls')),
    path("recruiter/", include("recruiter_app.urls")),
    path("applicant/", include("applicant_app.urls")),
    path("college/",include("college_app.urls")),
    path("select2/", include("django_select2.urls")),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
     path('converter/',include('htmltopdf.urls'),name="converter"),
    # path("signup/", views.signup, name = "signup")
]

accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('index/',views.index,name="index"),
    path('recruiter-signup/', views.recruiter_signup, name="recruiter-signup"),
    path('activate/<uid>/<token>/', views.activate, name='activate'),
    path('applicant-signup/', views.ApplicantSignUp, name="applicant-signup"),
    path('college-signup/', views.college_signup, name="college-signup"),
    path('email_form/',views.email_form,name="email_form"),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change_form.html",
                                                                   success_url=reverse_lazy(
                                                                       "accounts:password_change_done")),
         name="password_change"),
    path('change-password/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"),
         name="password_change_done"),
    path('applicant-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('applicant-signup/terms.html', views.showterms, name="showterms"),
    path('recruiter-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('recruiter-signup/terms.html', views.showterms, name="showterms"),
    path('college-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('college-signup/terms.html', views.showterms, name="showterms"),
    path('about/', views.about, name="about"),
]


applicant_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'applicant'

urlpatterns = [
    path("create-applicant-user-profile/", views.createprofile, name = "create_applicant_profile"),
    path("jobs-list", views.listjobs, name= "jobs_list"),
    path("job-detail/<int:pk>", views.job_detail, name = "job_detail"),
    path("applytojob/<int:pk>", views.applytojob, name = "applytojob"),
    path('activate/<uid>/<token>/', views.activate, name='activate'),
    path("job_search", views.job_search, name = "job_search"),
    path("job_alert", views.job_alert, name = "job_alert"),
    path("job_recommendations", views.job_recommendations, name = "job_recommendations"),
    path("job_companies", views.job_companies, name = "job_companies"),
    path("career_guidance", views.career_guidance, name = "career_guidance"),
    path("interview_tips", views.interview_tips, name = "interview_tips"),
    path("expert_call", views.expert_call, name = "expert_call"),
    path("matching_job", views.matching_job, name = "matching_job"),
    path("<int:pk>/view_profile/",views.view_profile,name="view_profile"),
    path('<int:pk>/edit_profile/', views.edit_profile, name='edit_profile'),
    path("search", views.search, name = "search"),
    # path('login/', auth_views.LoginView.as_view(),name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    # path('recruiter-signup/', views.RecruiterSignUp.as_view(), name="recruiter-signup"),
    # path('applicant-signup/', views.ApplicantSignUp.as_view(), name="applicant-signup"),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name = "accounts/password_change_form.html", success_url = reverse_lazy("accounts:password_change_done")), name = "password_change"),
    # path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/password_change_done.html"), name = "password_change_done"),
    

]

applicant_app/forms.py
from django import forms
from multiselectfield import MultiSelectFormField
from .models import ApplicantUserProfile

year=[tuple([x,x]) for x in range(1980,2020)]
class UserProfileForm(forms.ModelForm):
    # preferred_domain = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    skill_info = forms.MultipleChoiceField(choices=ApplicantUserProfile.SKILLS,required=False)
    class Meta:
        model = ApplicantUserProfile
        fields = ("headline","first_name","last_name","pheadline","current_position","education","country_region","location",
        "industry","contact_information","description","school_name","school_degree","field_of_study","location_of_school",
        "start_school","end_school","experience_title","company_name","company_location","start_company",
        "end_company", "area_of_expertise",
        "project_name","start_project","end_project","project_creator","associated_with",
        "project_url","project_description",
        "accomplishment_title","accomplishment_associated_with","issuer","issue_date","accomplishment_description","skill_info")
    pass

class UserProfileUpdationForm(forms.ModelForm):
    skill_info = forms.MultipleChoiceField(choices=ApplicantUserProfile.SKILLS,required=False)
    class Meta:
        model = ApplicantUserProfile
        fields = ("headline","first_name","last_name","pheadline","current_position","education","country_region","location",
        "industry","contact_information","description","school_name","school_degree","field_of_study","location_of_school",
        "start_school","end_school","experience_title","company_name","company_location","start_company",
        "end_company", "area_of_expertise",
        "project_name","start_project","end_project","project_creator","associated_with",
        "project_url","project_description",
        "accomplishment_title","accomplishment_associated_with","issuer","issue_date","accomplishment_description","skill_info")
    pass

class InputForm(forms.Form):

    fullname = forms.CharField(max_length = 200)
    mail = forms.EmailField()
    contact = forms.IntegerField()

applicant_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import UserProfileForm, InputForm, UserProfileUpdationForm
from .models import ApplicantUserProfile
from recruiter_app.models import Job, RecruiterUserProfile
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes,force_text,DjangoUnicodeDecodeError
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from accounts.models import ProfcessUser
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from .token import activation_token
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
# Create your views here.

@login_required
def view_profile(request, pk):
    try:
        UserProfileUpdationForm(instance=request.user.applicantuserprofile)
    except ObjectDoesNotExist:
        return redirect("applicant:create_applicant_profile")
    form = UserProfileUpdationForm(instance=request.user.applicantuserprofile)
    args = {'form': form}
    return render(request, "applicant_app/userprofileform.html", args)

@login_required
def createprofile(request):
    if request.method == "POST":
        print("hello")
        form = UserProfileForm(request.POST)
        if form.is_valid():
            userprofile = form.save(commit=False)
            userprofile.user = request.user
            userprofile.save()
            return render(request, "applicant_app/thanks.html") #return page after filling userinfo form

        else:
            return "#########"
        
    else:
        form = UserProfileForm()
        return render(request, "applicant_app/userprofileform.html", {"form":form})


@login_required
def applytojob(request, pk):
    """ Apply to a job  """
    context = {}
    job = Job.objects.get(pk=pk)
    context['job'] = job

    # If User has already applied redirect User to already applied page.
    if request.user in job.applied_by.all():
        return render(request, "applicant_app/applicationdonealready.html", context)

    log_in_user = ProfcessUser.objects.get(username=request.user.username)
    # if user is already activated then apply to job and show confiramtion
    if log_in_user.activated:
        # user object is is added to job with job id = pk
        job.applied_by.add(request.user)
        messages.success(request, 'Your application is received Recuiter will contact u soon')
        return render(request, "applicant_app/applytojob.html", context)
    else:
        # else send to index page where pop to verify email is shown
        return render(request, "applicant_app/verifyemailfirst.html", context)

@login_required
def listjobs(request):
    """
    Return a list of all jobs.

    """
    jobs = Job.objects.all()
    context = {
        "jobs":jobs
    }

    return render(request, "applicant_app/jobs_list.html", context)

@login_required
def job_detail(request, pk):
    
    job = get_object_or_404(Job, pk=pk)
    context = {
        "job":job,
    }
    
    return render(request, "applicant_app/job_detail.html", context)

@login_required
def mail(request):
        sub = forms.applicant_app()
        fullname = request.POST['fullname']
        mail = request.POST['mail']
        contact = request.POST['contact']
        recipient = str(sub['email'].value())
        send_mail('Verification', 'Applied successfully', 'contact@profcess.com', [recipient], fail_silently=False)
        return render(request,'applicant_app/mail.html')

def search(request):
    jobs = Job.objects.all()
    query_title=request.GET['query_title']
    query_skills=request.GET['query_skills']
    query_location=request.GET['query_location']
    if query_title != '' and  query_title is not None:
        jobs = Job.objects.filter(job_title__icontains=query_title)
    elif query_skills != '' and  query_skills is not None: 
        jobs = Job.objects.filter(job_requirements__icontains=query_skills)
    elif query_location != '' and  query_location is not None: 
        jobs = Job.objects.filter(job_location__icontains=query_location)

    context ={
        "jobs": jobs
    }
    return render(request, 'applicant_app/search.html',context)

def job_search(request):
    jobs = Job.objects.all()
    return render(request,"applicant_app/job_search.html",{'jobs':jobs})
@login_required
def matching_job(request):

    jobs={i:i.applied_by.count() for i in Job.objects.all()}
    sort_orders = sorted(jobs.items(), key=lambda x: x[1], reverse=True)
    my_context=[]
    for i in sort_orders:
        l1=list(i[0].job_requirements)
        l2=list(ApplicantUserProfile.objects.get(user=request.user).skill_info)
        if (all(x in l2 for x in l1)):
            my_context.append({'name':i[0]})
    return render(request,"applicant_app/matching_job.html",context={'jobs':my_context})


@login_required
def job_alert(request):
    return render(request,"applicant_app/job_alert.html")

@login_required
def job_recommendations(request):
    return render(request,"applicant_app/job_recommendations.html")

def job_companies(request):
    recruiter = RecruiterUserProfile.objects.all()
    return render(request,"applicant_app/job_companies.html",{'recruiter':recruiter})

@login_required
def career_guidance(request):
    return render(request,"applicant_app/career_guidance.html")

@login_required
def interview_tips(request):
    return render(request,"applicant_app/interview_tips.html")

@login_required
def expert_call(request):
    return render(request,"applicant_app/expert_call.html")


@login_required
def activate(request,uid,token):    #goes via mail
    return render(request,"applicant_app/activation.html")

@login_required
def edit_profile(request, pk):
    user = ProfcessUser.objects.get(id=pk)
    try:
        UserProfileUpdationForm(instance=request.user.applicantuserprofile)
    except ObjectDoesNotExist:
        return redirect("applicant:create_applicant_profile")
    form= UserProfileUpdationForm(instance=request.user.applicantuserprofile)
    if request.method == "POST":
        print("hello")
        form = UserProfileUpdationForm(request.POST, instance= request.user.applicantuserprofile)
        if form.is_valid():
            form.save()
            return render(request, "applicant_app/thanks.html")

    args = {'form': form}
    return render(request, 'applicant_app/userprofileform.html', args)

# @login_required
# def edit_profile(request, pk):
#     #user = User.objects.get(ApplicantUserProfile, pk=pk)
#     if request.method == "POST":
#         form = UserProfileForm(request.POST, instance=request.user)
#         if form.is_valid():
#             form.save()
#             #return redirect(('applicant:view_profile'))
#             return render(request, "applicant_app/thanks.html")


#     else:
#         form = UserProfileUpdationForm(instance=request.user)
#         context = {'form': form,}
#         return render(request, 'applicant_app/userprofileform.html', context)

applicant_app/templates/applicant_app/activate.html
{%autoescape off%}
Hi {{user.username}}
Thank You for registration in Profcess,
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'applicant:activate' uid=uid token=token%}
{%endautoescape%}

applicant_app/templates/applicant_app/activation.html
{% extends "base.html" %}


{% block content %}

<h1>Activation Successful!</h1>
    <div class='alert alert-info'></div>
    <h1>Activation Successful!</h1>
        <a href="{% url 'applicant:jobs_list' %}">Click to Continue</a>
    </div>
{% endblock content%}

applicant_app/templates/applicant_app/applicationdonealready.html
{% extends "dashboard.html" %}
{% block content %}
  <div class="container">
      <h1>Application to {{ job.job_title }} done already by {{ user.username }}
</h1>
  </div>
{% endblock content %}

applicant_app/templates/applicant_app/applytojob.html
{% extends "dashboard.html" %}
{% block content %}
  <div class="container">
      <h1>Successfully Applied to Job</h1>
  </div>
{% endblock content %}
Successfully Applied to Job

applicant_app/templates/applicant_app/career_guidance.html
{% extends "dashboard.html" %}
{% block content %}
<h1>
    guidance
</h1>
{% endblock content %}

applicant_app/templates/applicant_app/expert_call.html
{% extends "dashboard.html" %}
{% block content %}
<h1>
    expert call
</h1>
{% endblock content %}

applicant_app/templates/applicant_app/job_alert.html
{% extends "dashboard.html" %}
{% block content %}
<h1>
    job alert
</h1>
{% endblock content %}

applicant_app/templates/applicant_app/job_recommendations.html
{% extends "dashboard.html" %}
{% block content %}
<h1>
    Your recommendations
</h1>
{% endblock content %}

applicant_app/templates/applicant_app/job_search.html
{% extends "dashboard.html" %}
{% block content %}
<h1 style="color: darkblue;">
  Job Search
</h1>
{% if jobs %}
<ul style="list-style: none;">
  {% for jo in jobs %}
  <li>{{ jo.job_title }}</li>
  {% endfor %}
</ul>
{% else %}
<p>No job present.</p>
{% endif %}
{% endblock content %}

applicant_app/templates/applicant_app/matching_job.html

{% extends "dashboard.html" %}
{% block content %}
<h1>
    Matching job
</h1>
{%for job in jobs %}
<h2><a href="{% url 'applicant:job_detail' pk=job.name.pk %}">{{job.name.job_title}}</a> posted by {{job.name.company_name}}</h2>
{%endfor%}
{% endblock content %}

applicant_app/templates/applicant_app/search.html
{% extends "dashboard.html" %}

{% block content %}
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row py-4">
                    <div class="col-lg-12">
                        <h6 class="h2 text-white mb-3">Job Listing</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4 col-md-12">
                            <form  action="{% url 'applicant:search' %}" method="get" accept-charset="utf-8">
                                <div class="row align-items-center justify-content-center">
                                    <div class="col-md-1">
                                        <button class="btn bg-light searchbutton" type="submit">
                                          <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                    <div class="col-md-2">
                                        <input  id="query_title" name="query_title" type="text" placeholder="Search Job Title">
                                <!-- <button class="searchbutton" type="submit">
                                    <i class="fa fa-search"></i>
                                  </button> -->
                                  </div>
                                    <div class="col-md-2">
                                        <input  id="query_skills" name="query_skills" type="text" placeholder="Search by Skills">
                                    </div>
                                    <div class="col-md-2">
                                        <input  id="query_location" name="query_location" type="text" placeholder="Search by Location">
                                    </div>
                                </div>
                            </form>                 
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark mt-3">
                                <li class="breadcrumb-item"><a href="{% url 'applicant:jobs_list' %}"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item active" aria-current="page">jobsList</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid mt--6">
        <div class="row justify-content-center">
            <div class="col-md-8 col-12">
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header bg-transparent border-0">
                        <h1>Search Results</h1>
                    </div>
                    <!-- Translucent table -->
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col" class="sort" data-sort="name">JOB TITLE</th>
                            </tr>
                            </thead>
                            <tbody class="list">
                            {% if jobs|length < 1 %}
                            <p>
                                No search result found.

                                <!-- Your Search - <b>{{query_title}} </b>- did not match any Job.<br> -->

                                Suggestions:
                                <ul>
                                <li>
                                Try different keywords.
                                </li>
                                </ul>
                            </p>
                            {% endif %}
                            {% for job in jobs %}
                                <tr>
                                    <th scope="row">
                                        <a href="{% url 'applicant:job_detail' pk=job.pk %}">
                                            <div class="media align-items-center">
                                                <div class="media-body">
                                                    <span class="name mb-0 text-sm">{{ job.job_title }}</span><br>
                                                    <span class="pl-2 text-sm">Job Salary: {{ job.job_salary }}</span><br>
                                                    <span class="pl-2 text-sm">Company name: {{job.company_name}}</span><br>
                                                    <span class="pl-2 text-sm">Type of Job :{{job.type_of_job}}</span><br>
                                                    <span class="pl-2 text-sm">job Location :{{job.job_location}}</span><br>
                                                    <span class="pl-2 text-sm">job Requirements: {{job.job_requirements}}</span>

                                                </div>
                                            </div>
                                        </a>
                                    </th>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}


applicant_app/templates/applicant_app/thanks.html
{% extends "dashboard.html" %}
{% block content %}
  <div class="container">
      <h1>Thanks for filling up the profile.</h1>
  </div>
{% endblock content %}

applicant_app/templates/applicant_app/verifyemailfirst.html
{% extends "dashboard.html" %}
{% block content %}
  <div class="container">
      <h1>You have not verified your email yet. Kindly verify your email to apply for the job.
      <br> If you cannot find your confirmation email anymore, send yourself a new one here.
          <span><a href="{% url 'accounts:email_form' %}"><br>E-mail</a></span></h1>
  </div>
{% endblock content %}