Profcess_Dev/urls.py
from django.contrib import admin
from django.urls import path, include
# from test_app import views
from accounts import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("findJob/", views.findJob, name="findJob"),
    path("careerAdvice/", views.careerAdvice, name="careerAdvice"),
    path("findATalent/", views.findATalent, name="findATalent"),
    path("services/", views.services, name="services"),
    path("contact/", views.contact, name="contact"),
    path("accounts/", include('accounts.urls')),
    path("recruiter/", include("recruiter_app.urls")),
    path("applicant/", include("applicant_app.urls")),
    path("college/",include("college_app.urls")),
    path("select2/", include("django_select2.urls")),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
     path('converter/',include('htmltopdf.urls'),name="converter"),
    # path("signup/", views.signup, name = "signup")
]

accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('index/',views.index,name="index"),
    path('recruiter-signup/', views.recruiter_signup, name="recruiter-signup"),
    path('activate/<uid>/<token>/', views.activate, name='activate'),
    path('applicant-signup/', views.ApplicantSignUp, name="applicant-signup"),
    path('college-signup/', views.college_signup, name="college-signup"),
    path('email_form/',views.email_form,name="email_form"),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change_form.html",
                                                                   success_url=reverse_lazy(
                                                                       "accounts:password_change_done")),
         name="password_change"),
    path('change-password/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"),
         name="password_change_done"),
    path('applicant-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('applicant-signup/terms.html', views.showterms, name="showterms"),
    path('recruiter-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('recruiter-signup/terms.html', views.showterms, name="showterms"),
    path('college-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('college-signup/terms.html', views.showterms, name="showterms"),
    path('about/', views.about, name="about"),
]


applicant_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'applicant'

urlpatterns = [
    path("create-applicant-user-profile/", views.createprofile, name = "create_applicant_profile"),
    path("jobs-list", views.listjobs, name= "jobs_list"),
    path("job-detail/<int:pk>", views.job_detail, name = "job_detail"),
    path("applytojob/<int:pk>", views.applytojob, name = "applytojob"),
    path('activate/<uid>/<token>/', views.activate, name='activate'),
    path("job_search", views.job_search, name = "job_search"),
    path("job_alert", views.job_alert, name = "job_alert"),
    path("job_recommendations", views.job_recommendations, name = "job_recommendations"),
    path("job_companies", views.job_companies, name = "job_companies"),
    path("career_guidance", views.career_guidance, name = "career_guidance"),
    path("interview_tips", views.interview_tips, name = "interview_tips"),
    path("expert_call", views.expert_call, name = "expert_call"),
    path("matching_job", views.matching_job, name = "matching_job"),
    path("<int:pk>/view_profile/",views.view_profile,name="view_profile"),
    path('<int:pk>/edit_profile/', views.edit_profile, name='edit_profile'),
    path("search", views.search, name = "search"),
    # path('login/', auth_views.LoginView.as_view(),name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    # path('recruiter-signup/', views.RecruiterSignUp.as_view(), name="recruiter-signup"),
    # path('applicant-signup/', views.ApplicantSignUp.as_view(), name="applicant-signup"),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name = "accounts/password_change_form.html", success_url = reverse_lazy("accounts:password_change_done")), name = "password_change"),
    # path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/password_change_done.html"), name = "password_change_done"),
    

]

recruiter_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from recruiter_app.views import job_detail, Update_job,Delete_job,my_candidates,job_matching,search_candidates,campus_hiring,add_a_blog,assessments,recruiter_blog,applicant_detail


app_name = 'recruiter'

urlpatterns = [
    path("create-recruiter-user-profile/",
         views.createprofile, name="create_recruiter_profile"),
    path("profile/",views.profile,name="profile"),
    path("create-job/", views.createjob, name="create_job"),
    path("posted-jobs/", views.posted_jobs, name="posted_jobs"),
    path("job-detail/<int:pk>", views.job_detail, name="job_detail"),
    path("job-detail/<int:pk>/update/", Update_job.as_view(), name = "update_job"),
    path("job-detail/<int:pk>/delete/", Delete_job.as_view(), name = "delete_job"),
    path("search-candidates/",views.search_candidates,name="search_candidates"),
    path("my-candidate/", views.my_candidates, name="my_candidates"),
    path("job-matching/<int:pk>", views.job_matching, name="job_matching"),
    path("campus-hiring/", views.campus_hiring, name="campus_hiring"),
    path("assessments/", views.assessments, name="assessments"),
    path("add-a-blog/", views.add_a_blog, name="add_a_blog"),
    path("recruiter-blog/", views.recruiter_blog, name="recruiter_blog"),
    path("applicant-detail/<int:pk>", views.applicant_detail, name="applicant_detail"),
    path("can/<int:pk>/<int:mk>/",views.can,name="can"),
    path("alreadycan/<int:pk>/",views.alreadycan,name="alreadycan"),
    path("pricing/",views.pricing,name="pricing"),
    path("purchase-plan/",views.purchase_plan,name="purchase-plan")



    # path('login/', auth_views.LoginView.as_view(),name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    # path('recruiter-signup/', views.RecruiterSignUp.as_view(), name="recruiter-signup"),
    # path('applicant-signup/', views.ApplicantSignUp.as_view(), name="applicant-signup"),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name = "accounts/password_change_form.html", success_url = reverse_lazy("accounts:password_change_done")), name = "password_change"),
    # path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/password_change_done.html"), name = "password_change_done"),


]

templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<header class=" three headerTitle">
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class=" text-uppercase">About Us</h1>
            </div>
        </div>
    </div>
</header>
<section class="">
    <div class="container about">
        <div class="row">
            <div class="col">
                <h1>It's never about US, but always about YOU.
                    <br>But we do have our little story to tell.</h1>
            </div>

        </div>
    </div>
</section>
<section>
    <div id="sideBySideAbout" class="container col-md-8 col-10">
        <div class="row" data-aos-delay="10" data-aos="fade-right" data-aos-easing="ease-in-out"
            data-aos-duration="300">
            <div class="col-md-4 col-4">
                <img class="img-fluid" src="{% static 'img/info/1.png' %}" alt="stats">
            </div>
            <div class="col-md-8 col-8">
                <h1 class="text-center">Who We Are</h1>
                <ul class="text-justify">
                    <li>We are the story of work with a team of supercharged, talented, and experienced people along
                        with fresher who are highly ardent and can go to any extent to achieve the customary goal. </li>
                    <li>We will not bore you with our history, the number of locations we have or the awards we’ve won.
                    </li>
                    <li>What we do and why we do it is all you need to know.</li>
                </ul>
                <hr class="bg-primary p-1">
            </div>
        </div>
        <div class="row" data-aos-delay="10" data-aos="fade-left" data-aos="fade-left" data-aos-easing="ease-in-out"
            data-aos-duration="300">
            <div class="col-md-8 col-8 text-left">
                <h1 class="text-center">What We Do</h1>
                <ul class="text-justify">
                    <li>We help people ditch the script on the old ways of thinking and make the people-work connections
                        that enable the growth which job seekers and employers are striving for. </li>
                    <li>We're all about placing the right people in the right positions, not just filling a quota. We
                        listen to both the client and candidate's needs and ensure the entire process is a conversation,
                        not just a transaction. </li>
                    <li>We establish an ease in alliance between the company demand and skilled workforce through our
                        well-defined research and tech based platform which mainly monitors the real time market trend
                        and various diversified needs. </li>
                    <li>The alliance is established by assisting the company with a skilled workforce and providing the
                        opportunity to the talented candidates to update their employment status. </li>
                    <li>It's not a success until both our client and candidate are happy. Let us help you find success,
                        no matter which side of the process you're on.</li>
                </ul>
                <hr class="bg-primary p-1">
            </div>
            <div class="col-1"></div>
            <div class="col-md-3 col-3 d-flex align-items-center">
                <div class="text-right">
                    <img class="img-fluid" src="{% static 'img/info/2.png' %}" alt="stats">
                </div>
            </div>
        </div>
        <div class="row" data-aos-delay="10" data-aos-easing="ease-in-out" data-aos-duration="300">
            <div class="col-md-4 col-4">
                <img class="img-fluid" src="{% static 'img/info/3.png' %}" alt="stats">
            </div>
            <div class="col-md-8 col-8">
                <h1 class="text-center">Why We Do</h1>
                <ul class="text-justify">
                    <li>We live in a world where nothing is permanent, job seekers and employers are continually asking,
                        “What’s next?” The next chapter in life and quest for advancement means careers are continually
                        in motion. </li>
                    <li>The next business strategy and journey for growth means employers are continually testing their
                        workforce effectiveness. At Prof-cess, we always think about what’s next we have stored for you.
                    </li>
                    <li>We work to find answers to your question</li>
                </ul>
                <hr class="bg-primary p-1">
            </div>
        </div>
    </div> 
</section>
{% endblock %}

templates/baseDashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% if messages %}
<div class="card col-md-12 alert alert-warning" style="background-color:AntiqueWhite">
    <ul class="messages" style="text-align:center;color:black">
    {% for message in messages %}
    <span class="badge badge-danger">Warning</span>  {{ message }}
    <br<span><a href="{% url 'accounts:email_form' %}"><br>E-mail</a></span>
    {% endfor %}
    </ul>
</div>
    {% endif %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Prof-Cess Dashboard</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'assets/img/favicon.png' %}" type="image/png">
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'dashboard/vendor/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'dashboard/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}"
          type="text/css">
    <!-- Page plugins -->
    <!-- Argon CSS -->
    <link rel="stylesheet" href="{% static 'dashboard/css/argon.min.css' %}" type="text/css">
    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'dashboard/index.css' %}" type="text/css">
</head>

<body>
{% block menu %}{% endblock %}
<!-- Main content -->
<div class="main-content" id="panel">
    <!-- Topnav -->
    <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Navbar links -->
                <ul class="navbar-nav align-items-center ml-md-auto ">

                    <li class="nav-item d-xl-none">
                        <!-- Sidenav toggler -->
                        <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin"
                             data-target="#sidenav-main">
                            <div class="sidenav-toggler-inner">
                                <i class="sidenav-toggler-line"></i>
                                <i class="sidenav-toggler-line"></i>
                                <i class="sidenav-toggler-line"></i>
                            </div>
                        </div>
                    </li>
                    {% block navbar %} {% endblock %}
                </ul>
                <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
                    <li class="nav-item dropdown">
                        <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false">
                            <div class="media align-items-center">
                                    <span class="avatar avatar-sm rounded-circle">
                                        <img alt="Image placeholder"
                                             src="{% static 'dashboard/img/theme/person.png' %}">
                                    </span>
                                <div class="media-body  ml-2  d-none d-lg-block">
                                    <span class="mb-0 text-sm  font-weight-bold">{{ user.username }}</span>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-menu  dropdown-menu-right ">
                            <div class="dropdown-header noti-title">
                                <h6 class="text-overflow m-0">Welcome!</h6>
                            </div>
                            <a href="{% url 'applicant:edit_profile' pk=user.pk %}" class="dropdown-item">
                                <i class="ni ni-single-02"></i>
                                <span>My profile</span>
                            </a>
                            <a href="{% url 'accounts:password_change' %}" class="dropdown-item">
                                <i class="ni ni-settings-gear-65"></i>
                                <span>Change Password</span>
                            </a>
                            <div class="dropdown-divider"></div>
                            <a href="{% url 'accounts:logout' %}" class="dropdown-item">
                                <i class="ni ni-user-run"></i>
                                <span>Logout</span>
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Dashboard</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item"><a href="{% url 'index' %}"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Header -->
    {% block content %} {% endblock %}
    <!-- Page content -->
    <div class="container-fluid ">
        <!-- Footer -->
        <footer class="footer pt-0 ">
            <div class="row align-items-center justify-content-lg-between">
                <div class="col-lg-6">
                    <div class="copyright text-center  text-lg-left  text-muted">
                        &copy; 2020 <a href="{% url 'accounts:index' %}" class="font-weight-bold ml-1" target="_blank">Profcess</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                        <li class="nav-item">
                            <a href="{% url 'accounts:index' %}" class="nav-link" target="_blank">Prof-Cess</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'accounts:about' %}" class="nav-link" target="_blank">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'recruiter:recruiter_blog' %}" class="nav-link" target="_blank">Blog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>
</div>
<!-- Argon Scripts -->
<!-- Core -->
<script src="{% static 'dashboard/vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'dashboard/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'dashboard/vendor/js-cookie/js.cookie.js' %}"></script>
<script src="{% static 'dashboard/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
<script src="{% static 'dashboard/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
<!-- Optional JS -->
<script src="{% static 'dashboard/vendor/chart.js/dist/Chart.min.js' %}"></script>
<script src="{% static 'dashboard/vendor/chart.js/dist/Chart.extension.js' %}"></script>
<!-- Argon JS -->
<script src="{% static 'dashboard/js/argon.min.js' %}"></script>

{% block dashboardScripts %}

{% endblock %}
</body>
</html>

templates/careerAdvice.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
    <header class="masthead two headerTitle">
        <div class="container ">
            <div class="row">
                <div class="col">
                    <h1 class="masthead-heading text-uppercase">Career Advice</h1>
                </div>
            </div>
        </div>
    </header>
    <section>
        <div id="sideBySide" class="container col-10 col-md-7">
            <div class="row" data-aos="fade-right" data-aos-delay="10" data-aos-easing="ease-in-out"  data-aos-duration="300">
                <div class="col-3 col-md-2">
                    <img class="img-fluid" src="{% static 'img/candidateInfo/1.png' %}" alt="stats">
                </div>
                <div class="col-8 col-md-10">
                    <h2>Verified, up-to-date job listings</h2>
                    <p>Every day we signal jobs directly from employer. We’re committed to accurate, high-quality jobs
                        so you won’t find old, duplicated, or spammed listings here.</p>
                </div>
            </div>
            <div class="row" data-aos="fade-left" data-aos-delay="10" data-aos-easing="ease-in-out"  data-aos-duration="300">
                <div class="col-3 col-md-2"></div>
                <div class="col-6 col-md-8 text-left">
                    <h2>Seamless job search</h2>
                    <p>Organize and automate your job search while at home or on the go. <br/>We’ll deliver new,
                        relevant
                        jobs of interest straight to your inbox.</p>
                </div>
                <div class="col-3 col-md-2 text-right">
                    <img class="img-fluid" src="{% static 'img/candidateInfo/2.png' %}" alt="stats">
                </div>
            </div>
            <div class="row" data-aos="fade-right" data-aos-delay="10" data-aos-easing="ease-in-out"  data-aos-duration="300">
                <div class="col-3 col-md-2">
                    <img class="img-fluid" src="{% static 'img/candidateInfo/3.png' %}" alt="stats">
                </div>
                <div class="col-8 col-md-10">
                    <h2>Job Seeker and Employer connect</h2>
                    <p>For job seeker and employer connect - We want job seekers and employers to connect directly.
                        After you find the right job, you’re sent straight to the employer’s details to apply. No
                        fuss.</p>
                </div>
            </div>
        </div>

        <div class="container text-center">
            <div class="row">
                <div class="col">
                    <div class="m-5"></div>
                    <div class="row" id="path">
                        <div class="col-md-6 col-12 interviewTips">
                            <div>
                                <h2>TIPS FOR WRITING CV</h2>
                                <p>A Detailed document highlighting your professional and
                                    academic history.</p>
                                <!--<a class="btn btn-secondary" href="">READ MORE</a>-->
                            </div>
                        </div>
                        <div class="col-md-6 col-12 resumeTips">
                            <div>
                                <h2>TIPS FOR INTERVIEW</h2>
                                <p>A structured conversation where interviewer ask few
                                    questions and candidate is supposed to answer.</p>
                                <!--<a class="btn btn-primary" href="">READ MORE</a>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/findATalent.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<header class=" three headerTitle">
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class=" text-uppercase">About Us</h1>
            </div>
        </div>
    </div>
</header>
{% endblock %}

templates/services.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
    <header class="one headerTitle">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1 class="text-uppercase">Our services</h1>
                </div>
            </div>
        </div>
    </header>

    <section>
        <div id="recruiterServices" class="statsDiv container text-center">
            <div class="row">
                <div class="col-md-4 col-6">
                    <img class="img-fluid" src="{% static 'img/recruiterServices/1.png' %}" alt="stats">
                    <h4>Post a job</h4>
                    <p>Receive applications from interested candidates</p>
                </div>
                <div class="col-md-4 col-6">
                    <img class="img-fluid" src="{% static 'img/recruiterServices/2.png' %}" alt="stats">
                    <h4>Search Cv’s</h4>
                    <p>Search more than thousands Cv’s across industries career levels.</p>
                </div>
                <div class="col-md-4 col-6">
                    <img class="img-fluid" src="{% static 'img/recruiterServices/3.png' %}" alt="stats">
                    <h4>Branding Solutions</h4>
                    <p>Boost your employer brand with a company profile, branding solutions and your very own career
                        site</p>
                </div>
                <div class="col-md-4 col-6">
                    <img class="img-fluid" src="{% static 'img/recruiterServices/4.png' %}" alt="stats">
                    <h4>End to End Recruitment</h4>
                    <p>Tell us your criteria and our team of experts will take care of your hiring worries</p>
                </div>
                <div class="col-md-4 col-6">
                    <img class="img-fluid" src="{% static 'img/recruiterServices/5.png' %}" alt="stats">
                    <h4>Online Assessment</h4>
                    <p>Recruit quality candidates within less time and cost using our online assessments</p>
                </div>
                <div class="col-md-4 col-6">
                    <img class="img-fluid" src="{% static 'img/recruiterServices/6.png' %}" alt="stats">
                    <h4>Campus Recruitment</h4>
                    <p>With our strong network of campuses, we offer you the opportunity of hiring from the campus that
                        you are interested in.</p>
                </div>
            </div>
        </div>

        <div id="bannerPromote" class="container-fluid text-center bg-secondary text-light">
            <div class="row justify-content-center">
                <div class="col-10">
                    <h1>Explore our RPO and Hire the best Talent today </h1>
                    <h3>Free job posting and resume search for employer as part of our promotional campaign.</h3>
                    <a class="btn btn-primary" href="{% url 'recruiter:create_job' %}">Post a Job</a>
                </div>
            </div>
        </div>

        <div class="m-5"></div>
        <div id="sideBySide" class="container col-10 col-md-7">
            <div class="row" data-aos-delay="10" data-aos="fade-right" data-aos-easing="ease-in-out"  data-aos-duration="300">
                <div class="col-md-2 col-3" >
                    <img class="img-fluid" src="{% static 'img/recruiterI/1.png' %}" alt="stats">
                </div>
                <div class="col-md-10 col-9">
                    <h2>SEARCH TALENT</h2>
                    <p>Search results precisely to the criteria you set so we can connect you with best candidates Once
                        you post your job we provide you with best suited candidates for your job role.</p>

                </div>
            </div>
            <div class="row" data-aos-delay="10" data-aos="fade-left" data-aos="fade-left" data-aos-easing="ease-in-out"  data-aos-duration="300">
                <div class="col-md-2 col-3"></div>
                <div class="col-md-8 col-6 text-left">
                    <h2>REACH TOP TALENT</h2>
                    <p> Profcess's matching technology finds the right candidates, then invites them to apply. we’ve got
                        highly skilled and experienced candidates ready to go. The right fit can start today.</p>
                </div>
                <div class="col-md-2 col-3 text-right">
                    <img class="img-fluid" src="{% static 'img/recruiterI/2.png' %}" alt="stats">
                </div>
            </div>
            <div class="row" data-aos-delay="10" data-aos-easing="ease-in-out"  data-aos-duration="300">
                <div class="col-md-2 col-3">
                    <img class="img-fluid" src="{% static 'img/recruiterI/3.png' %}" alt="stats">
                </div>
                <div class="col-md-10 col-9">
                    <h2>REVIEW GREAT MATCHES</h2>
                    <p> as candidates apply, you can manage them in our all in one dashboard. Our staffing professionals
                        blend their expertise with matching technology that incorporates data.</p>
                </div>
            </div>
        </div>
    </section>

{% endblock %}